package postgres

import (
	"testing"
	"strings"
	"github.com/matryer/is"
)

func TestTablesTemplate(t *testing.T) {
	is := is.New(t)

	template, err := getTablesTemplate()
	is.NoErr(err)

	var writer strings.Builder

	data := TablesTemplateData{
		PackageName: "tables",
		Imports: []string{
			`sq "github.com/bokwoon95/go-structured-query"`,
		},
		Tables: []Table{
			{
				Name: "users",
				Schema: "public",
				StructName: "USERS",
				RawType: "BASE TABLE",
				Constructor: "TABLE_USERS",
				Fields: []TableField{
					{
						Name: "id",
						RawType: "integer",
						Type: FieldTypeNumber,
						Constructor: FieldConstructorNumber,
					},
					{
						Name: "first_name",
						RawType: "text",
						Type: FieldTypeString,
						Constructor: FieldConstructorString,
					},
					{
						Name: "date_created",
						RawType: "timestamp",
						Type: FieldTypeTime,
						Constructor: FieldConstructorTime,
					},
				},
			},
		},
	}

	err = template.Execute(&writer, data)
	is.NoErr(err)

	out := writer.String()

	expected := `// Code generated by 'sqgen-postgres tables'; DO NOT EDIT.
package tables

import (
	sq "github.com/bokwoon95/go-structured-query"
)

// USERS references the public.users table.
type USERS struct {
	*sq.TableInfo
	ID sq.NumberField
	FIRST_NAME sq.StringField
	DATE_CREATED sq.TimeField
}

// TABLE_USERS creates an instance of the public.users table.
func TABLE_USERS() USERS {
	tbl := USERS{TableInfo: &sq.TableInfo{
		Schema: "public",
		Name: "users",
	},}
	tbl.ID = sq.NewNumberField("id", tbl.TableInfo)
	tbl.FIRST_NAME = sq.NewStringField("first_name", tbl.TableInfo)
	tbl.DATE_CREATED = sq.NewTimeField("date_created", tbl.TableInfo)
	return tbl
}

// As modifies the alias of the underlying table.
func (tbl USERS) As(alias string) USERS {
	tbl.TableInfo.Alias = alias
	return tbl
}`
	is.Equal(len(out), len(expected))
	is.Equal(out, expected)
}
